version: "3.9"
services:
  slideshow:
    ports:
      - "8000:8000"
    image: lliwi/slideshow:base
    environment:
      - FLASK_DATABASE_HOST=
      - FLASK_DATABASE_USER=root
      - FLASK_DATABASE_PASSWORD=example
      - FLASK_DATABASE=slideshow
      - SECRET_KEY=yourseccret
    volumes:
      - ./app:/code/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
